### ISSUE TITLE
.desktop file doesn't launch the game

### ISSUE THREAD

**Issue by pizzadude** [flathub/ca.victorz.acr.AssaultCubeReloaded#1]
Launching the command from the .desktop file gives this error:

```
/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=acreloaded ca.victorz.acr.AssaultCubeReloaded
bwrap: execvp acreloaded: No such file or directory
```

However, simply typing "flatpak run ca.victorz.acr.AssaultCubeReloaded", the flatpak runs.

**Comment by Mailaender** [comment]
I agree that the naming might be confusing, but that is what upstream picked. The other binary is called `server` so there is some consistency.

**Comment by pizzadude** [comment]
So it is normal for the desktop file to not launch the flatpak? Sounds odd.

**Comment by pizzadude** [comment]
@hfiguiere command is set to acreloaded

**Comment by pizzadude** [comment]
I think you are misinterpreting me, what I mean is, in KDE's app menu, when I click "Assault Cube Reloaded" the game doesn't launch. That is because of "acreloaded" not existing. @hfiguiere @Mailaender

The launcher is broken.

**Comment by Mailaender** [comment]
Strange that there is no lint test for that. They are very picky for far less important things.

**Comment by hfiguiere** [comment]
+Exec=acreloaded

**Comment by hfiguiere** [comment]
this in the patch that create the .desktop

**Comment by Mailaender** [comment]
The patch was submitted upstream. `/usr/bin/client` would be too generic in FHS.
